

<!-- row start-->
      	<div class="row table-row">
        	<div class="col-sm-4 my-img hidden-xs"></div>
            <div class="col-sm-8">
            	<div class="content-box">
            	<h2 class="no-mar">Hi! I am Ventimiglia Samuel</h2>

                <h5 class="cd-headline clip is-full-width">I
                    <span class="cd-words-wrapper">
                        <b class="is-visible">am a Php backend Developer Zf expert</b>
                        <b>have 10+ years Experience</b>
                        <b>am Php Expert</b>
                        <b>love good code</b>
                    </span>
                </h5>
                <p>I am a resourceful person, cheerful and always ready to get involved.</p>
                <p>I never end my studies. I'm looking for a company where staff training is a commitment</p>
                <p><a href="#" class="btn btn-primary">Download Resume</a></p>
                </div>
            </div>
        </div>
        <!-- row end-->
        <!-- row start-->
      	<div class="overview-container">
        	<div class="overview-box color2">
            	<div class="grid-icon small"><i class="fa fa-birthday-cake"></i></div>
            	<h3>D.O.B</h3>
                <h5>18th October 1984</h5>
            </div>
            <div class="overview-box color3">
            	<div class="grid-icon small"><i class="fa fa-phone"></i></div>
            	<h3>Phone</h3>
                <h5><a href="tel:09876543210">+39 3495412814</a></h5>
            </div>
            <div class="overview-box color4">
            	<div class="grid-icon small"><i class="fa fa-at"></i></div>
            	<h3>Email</h3>
                <h5><a href="mailto:email@domain.com">info@samuelventimiglia.it</a></h5>
            </div>
            <div class="overview-box color5">
            	<div class="grid-icon small"><i class="fa fa-flag"></i></div>
            	<h3>Nationality</h3>
                <h5>Italian</h5>
            </div>
         </div>
      	<!-- row end-->
        <!-- row start -->
        <div class="row">
        	<div class="col-sm-12">
            	<div class="content-box">
                	<div class="row mar-50">
                        <div class="col-md-12">
                			<h4 class="heading text-center"><span>What can I do</span></h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-4">
                          <div class="service-box">
                            <i class="fa fa-gears"></i>
                            <h5>PHP Business Logic Application</h5>
                            <p>Analisys e development of logic operation of software.</p>
                             <div class="grid-icon small"><i class="fa fa-gears"></i></div>
                          </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                          <div class="service-box"> <i class="fa fa-fighter-jet"></i>
                            <h5>PHP Zend framework Application</h5>
                            <p>I have experience about zf2 - zf3 framework skeleton application.</p>
                             <div class="grid-icon small"><i class="fa fa-fighter-jet"></i></div>
                          </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                          <div class="service-box"> <i class="fa fa-code"></i>
                            <h5>PHP Web Application without framework</h5>
                            <p>Development free framework php application in front of client's request.</p>
                            <div class="grid-icon small"><i class="fa fa-code"></i></div>
                          </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                          <div class="service-box"> <i class="fa fa-line-chart"></i>
                            <h5>PHP Zend framework Module Design</h5>
                            <p>Development of module reusability.</p>
                            <div class="grid-icon small"><i class="fa fa-line-chart"></i></div>
                          </div>
                        </div>

                        <div class="col-md-4 col-sm-4">
                          <div class="service-box"> <i class="fa fa-cubes"></i>
                            <h5>PHP Zend framework single Module</h5>
                            <p>Development of single indipendent whereby reusable module.</p>
                             <div class="grid-icon small"><i class="fa fa-cubes"></i></div>
                          </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                          <div class="service-box"> <i class="fa fa-wordpress"></i>
                            <h5>Wordpress Site</h5>
                            <p>Hosting and Development of Awesome site under Wordpress.</p>
                             <div class="grid-icon small"><i class="fa fa-wordpress"></i></div>
                          </div>
                        </div>
						<div class="col-md-4 col-sm-4">
                          <div class="service-box"> <i class="fa fa-industry"></i>
                            <h5>Zend expressive - Bootstrap site</h5>
                            <p>Hosting and Development of Awesome site under Zend expressive - Bootstrap.</p>
                             <div class="grid-icon small"><i class="fa fa-industry"></i></div>
                          </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                          <div class="service-box"> <i class="fa fa-mobile"></i>
                            <h5>PHP Web App Development</h5>
                            <p>Development of mobile php web app.</p>
                             <div class="grid-icon small"><i class="fa fa-mobile"></i></div>
                          </div>
                        </div>
 						<div class="col-md-4 col-sm-4">
                          <div class="service-box"> <i class="fa fa-search"></i>
                            <h5>SEO</h5>
                            <p>Seo advisor.</p>
                             <div class="grid-icon small"><i class="fa fa-search"></i></div>
                          </div>
                        </div>

                </div>
            </div>
        </div>
        </div>
        <!-- row end -->