<!-- row start-->
      	<div class="row">
        	<div class="col-sm-12">
            	<div class="content-box">
                	<ul class="blog-list">
                    	<li style="background-image:url(include/images/blog-post1.jpg);">
                        	<a href="single-post.html">
                        	<h3>Certification about php</h3>
                            <h6>Category <span class="separator">|</span> <?= date('d - m -Y')?> <span class="separator">|</span> 23 comments</h6>
                            <em>read more</em>
                            </a>
                        </li>

                        <li style="background-image:url(include/images/blog-post2.jpg);">
                        	<a href="single-post.html">
                        	<h3>Praesent fringilla ex at massa consectetur finibus</h3>
                            <h6>Category <span class="separator">|</span> 2 Nov 2015 <span class="separator">|</span> 76 comments</h6>
                            <em>read more</em>
                            </a>
                        </li>

                        <li style="background-image:url(include/images/blog-post3.jpg);">
                        	<a href="single-post.html">
                        	<h3>Nulla rutrum nibh in accumsan venenatis</h3>
                            <h6>Category <span class="separator">|</span> 12 Oct 2015 <span class="separator">|</span> 173 comments</h6>
                            <em>read more</em>
                            </a>
                        </li>


                        <li style="background-image:url(include/images/blog-post4.jpg);">
                        	<a href="single-post.html">
                        	<h3>Duis laoreet est nec molestie volutpat</h3>
                            <h6>Category <span class="separator">|</span> 03 Oct 2015 <span class="separator">|</span> 87 comments</h6>
                            <em>read more</em>
                            </a>
                        </li>

                        <li style="background-image:url(include/images/blog-post5.jpg);">
                        	<a href="single-post.html">
                        	<h3>Consectetur adipisicing elit ipsum dolor sit amet</h3>
                            <h6>Category <span class="separator">|</span> 23 Sept 2015 <span class="separator">|</span> 23 comments</h6>
                            <em>read more</em>
                            </a>
                        </li>
                      </ul>

                    <nav class="text-center">
                      <ul class="pagination">
                        <li><a href="#"><i class="fa fa-angle-left"></i></a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                       <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                      </ul>
                    </nav>


                </div>
            </div>
        </div>
      	<!-- row end-->
