<div class="contact-content">
        <div class="map-container">
          <div id="map-canvas"></div>
        </div>
        <div class="content-box">
          <div class="contact-details">
            <h5 class="heading"><span>Get in Touch</span></h5>
            <p><i class="fa fa-map-marker"></i> Via Campanella, 41 <br/>
              Altissimo 36070, Vicenza Italy</p>
            <p><i class="fa fa-at"></i> <b>Email : </b> <a href="mailto:info@samuelventimiglia.it">info@samuelventimiglia.it</a></p>
            <p><i class="fa fa-phone"></i> <b>Phone : </b> <a href="tel:3495412814">+39 - 3495412814</a></p>
           <ul class="socialLinks">
            <li><a href="https://www.facebook.com/samuel.ventimiglia84" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li><a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></li>
            <li><a href="https://plus.google.com/u/0/+SamuelVentimiglia/posts" target="_blank"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="https://github.com/samuel20miglia" target="_blank"><i class="fa fa-github"></i></a></li>
            <li><a href="https://it.linkedin.com/in/ventimigliasamuel" target="_blank"><i class="fa fa-linkedin"></i></a></li>
          </ul>
          </div>
          <h4 class="heading"><span>Send me your problems!</span></h4>
          <p>It will be a pleasure to answer.</p>
          <!--  <form>-->
            <div class="form-group">
              <label>Name*</label>
              <input type="text" value="" id="name" name="name"  class="form-control" required />
            </div>
            <div class="form-group">
              <label>Email*</label>
              <input type="email" value="" id="email" name="email" class="form-control" required/>
            </div>
            <div class="form-group">
              <label>Subject</label>
              <input type="text" value="" id="subject" name="subject" class="form-control" required />
            </div>
            <div class="form-group">
              <label>Message*</label>
              <textarea class="form-control" id="body" name="body" required></textarea>
            </div>
            <div class="form-group text-right">
              <input type="button" value="Send Message" onclick="sendRequestMail()" class="btn btn-primary" />
            </div>
         <!--  </form> -->

        </div>
      </div>
