<?php $this->headTitle('Home'); ?>

<ul class="grid-nav">
    <li class="animsition" data-animsition-in-class="fade-in-down-lg" data-animsition-in-duration="300" data-animsition-out-class="zoom-out-lg" data-animsition-out-duration="500">
    	<div class="head">John Doe</div>
    </li>

    <li class="animsition" data-animsition-in-class="fade-in-down-lg" data-animsition-in-duration="300" data-animsition-out-class="zoom-out-lg" data-animsition-out-duration="500">
    	<a href="about.html" class="animsition-link">
  		<div>
        	<div class="grid-icon"><i class="fa fa-user-secret"></i></div>
  			<h2>About</h2>
            <p class="cd-headline clip is-full-width">
                <span class="cd-words-wrapper">
                    <b class="is-visible">HTML Developer</b>
                    <b>5+ Years Experience</b>
                    <b>Responsive Expert</b>
                </span>
            </p>
            <em>view</em>
       </div>
       </a>
   </li>

   <li class="animsition" data-animsition-in-class="fade-in-down-lg" data-animsition-in-duration="300" data-animsition-out-class="zoom-out-lg" data-animsition-out-duration="500">
    	<a href="resume.html" class="animsition-link">
  		<div>
        	<div class="grid-icon"><i class="fa fa-file-text"></i></div>
  			<h2>Resume</h2>
            <p class="cd-headline clip is-full-width">
                <span class="cd-words-wrapper">
                    <b class="is-visible">Education</b>
                    <b>Experiences</b>
                    <b>Skills</b>
                </span>
            </p>
            <em>view</em>
       </div>
       </a>
   </li>

   <li class="animsition" data-animsition-in-class="fade-in-up-lg" data-animsition-in-duration="300" data-animsition-out-class="zoom-out-lg" data-animsition-out-duration="500">
    	<a href="portfolio.html" class="animsition-link">
  		<div>
        	<div class="grid-icon"><i class="fa fa-suitcase"></i></div>
  			<h2>Portfolio</h2>
            <p class="cd-headline clip is-full-width">
                <span class="cd-words-wrapper">
                    <b class="is-visible">Projects</b>
                    <b>Clients</b>
                    <b>Testimonials</b>
                </span>
            </p>
            <em>view</em>
       </div>
       </a>
   </li>

   <li class="animsition" data-animsition-in-class="fade-in-up-lg" data-animsition-in-duration="300" data-animsition-out-class="zoom-out-lg" data-animsition-out-duration="500">
    	<a href="blog.html" class="animsition-link">
  		<div>
        	<div class="grid-icon"><i class="fa fa-tags"></i></div>
  			<h2>Blog</h2>
            <p class="cd-headline clip is-full-width">
                <span class="cd-words-wrapper">
                    <b class="is-visible">Awesome Posts</b>
                    <b>Many Categories</b>
                </span>
            </p>
            <em>view</em>
       </div>
       </a>
   </li>


   <li class="animsition" data-animsition-in-class="fade-in-up-lg" data-animsition-in-duration="300" data-animsition-out-class="zoom-out-lg" data-animsition-out-duration="500">
    	<a href="contact.html" class="animsition-link">
  		<div>
        	<div class="grid-icon"><i class="fa fa-phone"></i></div>
  			<h2>Contact</h2>
            <p class="cd-headline clip is-full-width">
                <span class="cd-words-wrapper">
                    <b class="is-visible">Say Hello</b>
                    <b>Contact Details</b>
                    <b>Social Links</b>
                </span>
            </p>
            <em>view</em>
       </div>
       </a>
   </li>

</ul>
