<!-- row start-->
      	<div class="row">
        	<div class="col-sm-12">
            	<div class="content-box">
                	<ul class="project-category">
                        <li><a href="#" data-filter="" id="option1" class="active">All</a></li>
                        <li><a href="#" data-filter="one" id="option1" class="">Software</a></li>
                        <li><a href="#" data-filter="two" id="option2" class="">Web app</a></li>
                        <li><a href="#" data-filter="three" id="option3" class="">Websites</a></li>
                        <li><a href="#" data-filter="four" id="option4" class="">Seo</a></li>
                    </ul>

    			 <div  id="masonry"  class="grid">
                      <div class="grid-sizer"></div>
                      <div class="gutter-sizer"></div>

                      <div data-filter="one" class="grid-item">
                        <img src="/images/1.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="two" class="grid-item">
                        <img src="/images/7.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="three" class="grid-item">
                        <img src="/images/3.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="four" class="grid-item">
                        <img src="/images/4.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="one" class="grid-item">
                        <img src="/images/5.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="two" class="grid-item">
                        <img src="/images/6.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="three" class="grid-item">
                        <img src="/images/7.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="four" class="grid-item">
                        <img src="/images/1.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="one" class="grid-item">
                        <img src="/images/2.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="two" class="grid-item">
                        <img src="/images/3.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="three" class="grid-item">
                        <img src="/images/4.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>

                      <div data-filter="four" class="grid-item">
                        <img src="/images/5.jpg" alt="" />
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <a href="#" class="zoom" data-toggle="modal" data-target="#projectModal"><i class="fa fa-search"></i></a>
                                <a href="http://www.google.com" class="link" target="_blank"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                      </div>
                    </div>

                 </div>


                 <div class="content-box text-center">
                 	<h4 class="heading"><span>Clients</span></h4>
                    <div class="flexslider2">
                    <ul class="clients-list slides">
                        <li><img src="/images/clients/client1.png" alt="">Hostaria Verona</li>
                        <li><img src="/images/clients/client2.png" alt="">Tierre</li>
                        <li><img src="/images/clients/client3.png" alt="">Buonforno</li>
                        <li><img src="/images/clients/client1.png" alt="">Soloinvetrina</li>
                        <li><img src="/images/clients/client2.png" alt="">Aesse Portoni</li>
                        <li><img src="/images/clients/client3.png" alt="">Info legal</li>
                        <li><img src="/images/clients/client1.png" alt=""></li>
                        <li><img src="/images/clients/client2.png" alt=""></li>
                        <li><img src="/images/clients/client3.png" alt=""></li>
                    </ul>
                    </div>
                 </div>
                 <div class="content-box text-center">
                 	<h4 class="heading"><span>Testimonials</span></h4>
                     <div class="testimonial-container">
                <div class="flexslider">
                     <ul class="slides">
						 <li>
                            	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero. Curabitur vulputate vestibulum elementum. Suspendisse id neque a nibh mollis blandit. Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero. Suspendisse id neque a nibh mollis blandit. Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero.</p>
                                <div class="testimonial-by">
                                    <h6> Client Name<span>company name</span></h6>
                                </div>
                        </li>
                        <li>
                            	<p>Suspendisse id neque a nibh mollis blandit. Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero. Curabitur vulputate vestibulum elementum.</p>
                               <div class="testimonial-by">
                                    <h6> Client Name<span>company name</span></h6>
                                </div>
                        </li>
                        <li>
                        	<p>Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero. Curabitur vulputate vestibulum elementum. Suspendisse id neque a nibh mollis blandit. Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero. Suspendisse id neque a nibh mollis blandit.</p>
                               <div class="testimonial-by">
                                    <h6> Client Name<span>company name</span></h6>
                                </div>
                        </li>
                    </ul>
                  </div>
                </div>
                 </div>
            </div>
        </div>
      	<!-- row end-->
