<!-- row start-->
<div class="row">
	<div class="col-sm-12">
		<div class="content-box">
			<ul class="project-category">
				<li><a href="#" data-filter="" id="option1" class="active">All</a></li>
				<li><a href="#" data-filter="one" id="option1" class="">Software</a></li>
				<li><a href="#" data-filter="two" id="option2" class="">Web app</a></li>
				<li><a href="#" data-filter="three" id="option3" class="">Libraries</a></li>
				<!-- <li><a href="#" data-filter="four" id="option4" class="">Seo</a></li> -->
			</ul>

			<div id="masonry" class="grid">
				<div class="grid-sizer"></div>
				<div class="gutter-sizer"></div>
				<div data-filter="one" class="grid-item">
					<!--                         <img src="/images/3.jpg" alt="" /> -->
					<h5>
						<i>SmartFiera</i>
					</h5>
					<div class="portfolio-hover">
						<div class="portfolio-hover-content" style="z-index: 1500">
							<article class="link" >ERP For the kind of exhibition activities,
								we have created a truly innovative system simply based on controll panel and apps
								for smartphones with a powerfull realtime.</article>
						</div>
					</div>
				</div>
				<div data-filter="one" class="grid-item">
					<!--                         <img src="/images/1.jpg" alt="" /> -->
					<h5>
						<i>Gestionale web Multiazienda</i>
					</h5>
					<div class="portfolio-hover">
						<div class="portfolio-hover-content">
							<article class="link">Software for plastic industry</article>

						</div>
					</div>
				</div>

				<div data-filter="two" class="grid-item">
					<!--                         <img src="/images/7.jpg" alt="" /> -->
					<h5>
						<i>Gestionale web Multiazienda</i>
					</h5>
					<div class="portfolio-hover">
						<div class="portfolio-hover-content">
							<article class="link">
								Software for food industry<br> PHP + zend framework, bootstrap
							</article>

						</div>
					</div>
				</div>

				<div data-filter="three" class="grid-item">
					<!--                         <img src="/images/3.jpg" alt="" /> -->
					<h5>
						<i>PHP7 Firebase Library</i>
					</h5>
					<div class="portfolio-hover">

						<div class="portfolio-hover-content">
							<article class="link">This lib can manage rest,stream and rules
								operations</article>
							<br> <a href="#" class="zoom" data-toggle="modal"
								data-target="#projectModal"><i class="fa fa-search"></i> </a> <a
								href="https://github.com/samuel20miglia/zend_Firebase"
								class="link" target="_blank"><i class="fa fa-link"></i></a>
						</div>
					</div>
				</div>

				<div data-filter="one" class="grid-item">
					<!--                         <img src="/images/3.jpg" alt="" /> -->
					<h5>
						<i>Qrcode generator</i>
					</h5>
					<div class="portfolio-hover">
						<div class="portfolio-hover-content">
							<article class="link">Web application to create milion of qrcode.
							</article>
						</div>
					</div>
				</div>

				<div data-filter="one" class="grid-item">
					<!--                         <img src="/images/3.jpg" alt="" /> -->
					<h5>
						<i>Tulain software</i>
					</h5>
					<div class="portfolio-hover" >
						<div class="portfolio-hover-content" style="z-index: 1500">
							<article class="link" >For companies in the Italian brewing
								industry to differentiate themselves from the competition and
								improve their cost management proposes an innovative system
								based on an app for smartphones and an online control panel. New
								marketing concept.</article>
						</div>
					</div>
				</div>

				<div data-filter="two" class="grid-item">
					<!--                         <img src="/images/3.jpg" alt="" /> -->
					<h5>
						<i>B2B web app</i>
					</h5>
					<div class="portfolio-hover">
						<div class="portfolio-hover-content">
							<article class="link">Web app dedicated to your agent.
							They can insert orders, create reports, show statistics.
							Always in mobility.
							</article>
						</div>
					</div>
				</div>

				<div data-filter="one" class="grid-item">
					<!--                         <img src="/images/3.jpg" alt="" /> -->
					<h5>
						<i>ItbBadge</i>
					</h5>
					<div class="portfolio-hover">
						<div class="portfolio-hover-content">
							<article class="link">Web app to manage emplooyers</article>

						</div>
					</div>
				</div>

				<div data-filter="one" class="grid-item">
					<!--                         <img src="/images/3.jpg" alt="" /> -->
					<h5>
						<i>Tracking Food</i>
					</h5>
					<div class="portfolio-hover">
						<div class="portfolio-hover-content">
							<article class="link">Web application to manage batch within
								industrial processes</article>
						</div>
					</div>
				</div>

				<div data-filter="two" class="grid-item">
					<!--                         <img src="/images/3.jpg" alt="" /> -->
					<h5>
						<i>Raspberry Video Inspector storage</i>
					</h5>
					<div class="portfolio-hover">
						<div class="portfolio-hover-content">
							<article class="link">Simple but very awesome system to manage
								video and reports of flue inspection.</article>
						</div>
					</div>
				</div>
			</div>

		</div>


<!-- 		<div class="content-box text-center"> -->
<!-- 			<h4 class="heading"> -->
<!-- 				<span>Clients</span> -->
<!-- 			</h4> -->
<!-- 			<div class="flexslider2"> -->
<!-- 				<ul class="clients-list slides"> -->
<!-- 					<li>Hostaria Verona</li> -->
<!-- 					<li>Tierre</li> -->
<!-- 					<li>Buonforno</li> -->
<!-- 					<li>Soloinvetrina</li> -->
<!-- 					<li>Aesse</li> -->
<!-- 					<li>Info legal</li> -->
<!-- 				</ul> -->
<!-- 			</div> -->
<!-- 		</div> -->
		<div class="content-box text-center">
			<h4 class="heading">
				<span>Testimonials</span>
			</h4>
			<div class="testimonial-container">
				<div class="flexslider">
					<ul class="slides">
						<li>
							<p>E' una persona capace di svolgere il suo lavoro in modo
								impeccabile, un bravo programmatore ed un ottimo elemento per un
								team di sviluppo. Ha una conoscenza molto ampia su quasi tutto
								il mondo del "web-development".</p>
							<div class="testimonial-by">
								<h6>
									Davide Biasin<span>Tierre s.r.l.</span>
								</h6>
							</div>
						</li>
						<li>
							<p>Ottima analisi.</p>
							<div class="testimonial-by">
								<h6>
									20% di margine in piu' in un solo mese<span>Gruppo Pam</span>
								</h6>
							</div>
						</li>
						<li>
							<p>Tutte le aziende dovrebbero avere un informatico.</p>
							<div class="testimonial-by">
								<h6>
									AD Soloinvetrina<span>soloinvetrina s.r.l.s.</span>
								</h6>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- row end-->
