<!-- row start -->
        <div class="container-fluid">
        <div class="row">
        <!-- col start -->
        	<div class="col-md-4">
            	<div class="row">
                        <div class="col-md-12">
                        	<div class="content-box no-side-pad">
                			<h4 class="heading"><span>Experience</span></h4>
                            <ul class="resume-list">
                            	<li>
                                	<div class="resume-title">
                                    	<div class="resume-icon">
                                        	<i class="fa fa-briefcase"></i>
                                    	</div>
                                        <h5>Tierre s.r.l..</h5>
                                        <span>PhP Backend Developer - Full stack</span>
                                    </div>
                                    <div class="resume-content">
                                     <b>2015 - Current</b>
                                     <p>Analyst and Developer of management softwares like Tulain software.</p>
                                     <div class="grid-icon small"><i class="fa fa-briefcase"></i></div>
                                     </div>

                          		</li>

                                <li>
                                	<div class="resume-title">
                                    	<div class="resume-icon">
                                        	<i class="fa fa-send-o"></i>
                                    	</div>
                                        <h5>Buonforno s.r.l.</h5>
                                        <span>IT Manager - PhP Developer</span>
                                    </div>
                                    <div class="resume-content">
                                     <b>2010 - 2015 - <small>4 years and 4 months</small></b>
                                     <p>IT Manager - PhP full stack web developer i was created and managed all intranet, linux servers and i was created 6 software for food industry.</p>
                                     <div class="grid-icon small"><i class="fa fa-send-o"></i></div>
                                     </div>

                          		</li>

                                <li>
                                	<div class="resume-title">
                                    	<div class="resume-icon">
                                        	<i class="fa fa-bullhorn"></i>
                                    	</div>
                                        <h5>Soloinvetrina s.r.l.</h5>
                                        <span>Junior PhP Developer</span>
                                    </div>
                                    <div class="resume-content">
                                     <b>2005 - 2009 - <small>3 years</small></b>
                                     <p>Developer of websites and internal software to manage Industry processes, financial statements, tax records</p>
                                     <div class="grid-icon small"><i class="fa fa-bullhorn"></i></div>
                                     </div>

                          		</li>
                               </ul>


                        </div>
                    </div>
              </div>
        </div>
        <!-- col end -->

        <!-- col start -->
        	<div class="col-md-4">
            	<div class="row">
                        <div class="col-md-12">
                        <div class="content-box no-side-pad">
                			<h4 class="heading"><span>Education</span></h4>
                            <ul class="resume-list">
                            	<li>
                                	<div class="resume-title">
                                    	<div class="resume-icon">
                                        	<i class="fa fa-university"></i>
                                    	</div>
                                        <h5>Php Unit Testing Course</h5>
                                        <span>All aspects of test and zf integration.</span>
                                    </div>
                                    <div class="resume-content">
                                     <b>2016 - 2016</b>
                                     <p>Installing, phpunit in IDE, introduction to tests, test dependencies and exceptions, tests from command line, test isolation and interaction, using test doubles, testing databases, testing APIs, testing legacy code, test in the browser, continuos integration, phpunit alternateves, extentions, relatives, bdd.</p>
                                      <div class="grid-icon small"><i class="fa fa-university"></i></div>
                                      </div>

                          		</li>

                                <li>
                                	<div class="resume-title">
                                    	<div class="resume-icon">
                                        	<i class="fa fa-laptop"></i>
                                    	</div>
                                        <h5>Zend PhP Course</h5>
                                        <span>Programming Design Patter and Best Practice</span>
                                    </div>
                                    <div class="resume-content">
                                     <b>2012 - 20013</b>
                                     <p>Model View Controller Application.</p>
                                     <div class="grid-icon small"><i class="fa fa-laptop"></i></div>
                                     </div>

                          		</li>

                                <li>
                                	<div class="resume-title">
                                    	<div class="resume-icon">
                                        	<i class="fa fa-android"></i>
                                    	</div>
                                        <h5>J2EE Course</h5>
                                        <span>Java For Web Application</span>
                                    </div>
                                    <div class="resume-content">
                                     <b>2010 - 2011</b>
                                     <p>Java language, Jboss, tomcat.</p>
                                     <div class="grid-icon small"><i class="fa fa-android"></i></div>
                                     </div>

                          		</li>

                               </ul>
                        </div>
                    </div>
              </div>
        </div>
        <!-- col end -->

        <!-- col start -->
        	<div class="col-md-4">
            	<div class="row">
                        <div class="col-md-12">
                        <div class="content-box no-side-pad">
                			<h4 class="heading"><span>Skills</span></h4>
                            <ul class="resume-list">
                            	<li>
                                	<div class="resume-title">
                                    	<div class="resume-icon">
                                        	<i class="fa fa-magic"></i>
                                    	</div>
                                        <h5 class="one-line">Professional Skills</h5>

                                    </div>
                                    <div class="resume-content">
                                         <div class="progress-box">
                                            <p>PhP</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100" style="width: 98%"><span class="sr-only">98%</span></div>
                                            </div>
                                          </div>

										 <div class="progress-box">
                                            <p>SQL</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"><span class="sr-only">80%</span></div>
                                            </div>
                                          </div>
                                         <div class="progress-box">
                                            <p>HTML 5</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%"><span class="sr-only">95%</span></div>
                                            </div>
                                          </div>

                                          <div class="progress-box">
                                            <p>CSS</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%"><span class="sr-only">90%</span></div>
                                            </div>
                                          </div>


                                         <div class="progress-box">
                                            <p>jQuery</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"><span class="sr-only">75%</span></div>
                                            </div>
                                          </div>

                                          <div class="progress-box">
                                            <p>javascript</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"><span class="sr-only">80%</span></div>
                                            </div>
                                          </div>

										 <div class="progress-box">
                                            <p>OOP</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"><span class="sr-only">100%</span></div>
                                            </div>
                                          </div>

                                          <div class="progress-box">
                                            <p>Rest</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%"><span class="sr-only">95%</span></div>
                                            </div>
                                          </div>
                                          <div class="progress-box">
                                            <p>Zend Framework</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%"><span class="sr-only">95%</span></div>
                                            </div>
                                          </div>

                                          <div class="progress-box">
                                            <p>Doctrine</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"><span class="sr-only">80%</span></div>
                                            </div>
                                          </div>

                                          <div class="progress-box">
                                            <p>Git</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"><span class="sr-only">75%</span></div>
                                            </div>
                                          </div>


                                         <div class="progress-box">
                                            <p>WordPress</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100" style="width: 55%"><span class="sr-only">55%</span></div>
                                            </div>
                                          </div>

                                          <div class="progress-box">
                                            <p>API</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%"><span class="sr-only">95%</span></div>
                                            </div>
                                          </div>

                                          <div class="progress-box">
                                            <p>Web Service</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%"><span class="sr-only">90%</span></div>
                                            </div>
                                          </div>


                                     </div>
                                     <div class="grid-icon small"><i class="fa fa-magic"></i></div>


                          		</li>

                                <li>
                                	<div class="resume-title">
                                    	<div class="resume-icon">
                                        	<i class="fa fa-language"></i>
                                    	</div>
                                        <h5 class="one-line">Language Skills</h5>

                                    </div>
                                    <div class="resume-content">
                                         <div class="progress-box">
                                            <p>English</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%"><span class="sr-only">85%</span></div>
                                            </div>
                                          </div>


                                         <div class="progress-box">
                                            <p>Italian native language
                                            </p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"><span class="sr-only">100%</span></div>
                                            </div>
                                          </div>



                                         <div class="progress-box">
                                            <p>French</p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%"><span class="sr-only">25%</span></div>
                                            </div>
                                          </div>

                                     </div>
                                     <div class="grid-icon small"><i class="fa fa-language"></i></div>


                          		</li>
                            </ul>
                        </div>
                    </div>
              </div>
        </div>
        <!-- col end -->

        </div>
        </div>
        <!-- row end -->

        <!-- row start-->
      	<div class="overview-container">
        	<div class="overview-box color1">
            	<div class="grid-icon small"><i class="fa fa-suitcase"></i></div>
            	<h1>18+</h1>
                <h5>Projects Done</h5>
            </div>
            <div class="overview-box color3">
            	<div class="grid-icon small"><i class="fa fa-smile-o"></i></div>
            	<h1>All</h1>
                <h5>Happy Clients</h5>
            </div>
      <div class="overview-box color4">
            	<div class="grid-icon small"><i class="fa fa-flag"></i></div>
            	<h1>3</h1>
                <h5>Countries Served</h5>
            </div>
            <div class="overview-box color5">
            	<div class="grid-icon small"><i class="fa fa-trophy"></i></div>
            	<h1>1</h1>
                <h5>Zend Certification</h5>
            </div>
         </div>
      	<!-- row end-->
